// Code generated by BobGen sqlite v0.29.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

// Make sure the type Patient runs hooks after queries
var _ bob.HookableType = &Patient{}

// Make sure the type Procedure runs hooks after queries
var _ bob.HookableType = &Procedure{}

// Make sure the type Setting runs hooks after queries
var _ bob.HookableType = &Setting{}

// Make sure the type decimal.Decimal satisfies database/sql.Scanner
var _ sql.Scanner = (*decimal.Decimal)(nil)

// Make sure the type decimal.Decimal satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(decimal.Decimal)
