// Code generated by tygo. DO NOT EDIT.

//////////
// source: module.go

export type SettingType = string;
export const PatientType: SettingType = "PatientType";
export const ProcedureType: SettingType = "ProcedureType";

//////////
// source: view.go

export interface ViewProcedure {
  id: number;
  type: string | null;
  date: string | null;
  details: string | null;
  patientId: number | null;
}
export interface ViewPatient {
  id: number | undefined;
  type: string | null;
  name: string | null;
  gender: 'unknown' | 'male' | 'female';
  age: number | null;
  chipId: number | null;
  weight: number | null;
  castrated: number | null;
  folder: number | null;
  indexFolder: number | null;
  note: string | null;
  owner: string | null;
  ownerPhone: string | null;
  procedures: ViewProcedure[];
}
export interface ViewSetting {
  id: number | undefined;
  type: 'PatientType' | 'ProcedureType' | 'PatientFolder';
  value: string | null;
  index: number | null;
}
export interface ViewError {
  error: string;
}
