// Code generated by tygo. DO NOT EDIT.

//////////
// source: module.go

export type SettingType = string;
export const PatientType: SettingType = "PatientType";
export const ProcedureType: SettingType = "ProcedureType";

//////////
// source: view.go

export interface ViewProcedure {
  id?: number /* int64 */;
  type?: string;
  date?: string;
  details?: string;
  patientId: number /* int64 */;
}
export interface ViewListPatient {
  id: number /* int64 */;
  type: string;
  name: string;
  chipId: string;
  owner: string;
  phone: string;
}
export interface ViewPatient {
  id?: number /* int64 */;
  type?: string;
  name?: string;
  gender?: 'unknown' | 'male' | 'female';
  age?: number;
  chipId?: string;
  weight?: number /* float64 */;
  castrated?: number;
  note?: string;
  owner?: string;
  ownerPhone?: string;
  procedures?: ViewProcedure[];
}
export interface ViewSetting {
  id?: number /* int64 */;
  type: 'PatientType' | 'ProcedureType';
  value: string;
  index: number /* uint */;
}
export interface ViewError {
  error: string;
}
