// Code generated by tygo. DO NOT EDIT.

//////////
// source: main.go

export interface Procedure {
  id: string /* uuid */;
  type: string;
  date: string;
  details: string;
}

export interface ListPatient {
  id: string /* uuid */;
  type: string;
  name: string;
  chipId: string;
  owner: string;
  phone: string;
}

export interface Patient {
  id: string /* uuid */;
  type: string;
  name: string;
  gender: 'unknown' | 'male' | 'female';
  birthDate: string;
  chipId: string;
  weight: number /* float64 */;
  castrated: boolean;
  lastModified: string;
  note: string;
  owner: string;
  ownerPhone: string;
  procedures: Procedure[];
}
