// Code generated by tygo. DO NOT EDIT.

//////////
// source: main.go

export interface Patient {
  Id: string /* uuid */;
  Type: string;
  Name: string;
  Gender: string;
  BirthDate: string;
  ChipId: string;
  Weight: number /* float64 */;
  Castrated: boolean;
  LastModified: string;
  Note: string;
  Owner: string;
  OwnerPhone: string;
}

//////////
// source: view.go

export interface ViewProcedure {
  id: string /* uuid */;
  type: string;
  date: string;
  details: string;
}
export interface ViewListPatient {
  id: string /* uuid */;
  type: string;
  name: string;
  chipId: string;
  owner: string;
  phone: string;
}
export interface ViewPatient {
  id: string /* uuid */;
  type: string;
  name: string;
  gender: 'unknown' | 'male' | 'female';
  birthDate: string;
  chipId: string;
  weight: number /* float64 */;
  castrated: boolean;
  lastModified: string;
  note: string;
  owner: string;
  ownerPhone: string;
  procedures: ViewProcedure[];
}
