// Code generated by BobGen sqlite v0.29.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	basePatientMods   PatientModSlice
	baseProcedureMods ProcedureModSlice
	baseSettingMods   SettingModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewPatient(mods ...PatientMod) *PatientTemplate {
	o := &PatientTemplate{f: f}

	if f != nil {
		f.basePatientMods.Apply(o)
	}

	PatientModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewProcedure(mods ...ProcedureMod) *ProcedureTemplate {
	o := &ProcedureTemplate{f: f}

	if f != nil {
		f.baseProcedureMods.Apply(o)
	}

	ProcedureModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewSetting(mods ...SettingMod) *SettingTemplate {
	o := &SettingTemplate{f: f}

	if f != nil {
		f.baseSettingMods.Apply(o)
	}

	SettingModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBasePatientMods() {
	f.basePatientMods = nil
}

func (f *Factory) AddBasePatientMod(mods ...PatientMod) {
	f.basePatientMods = append(f.basePatientMods, mods...)
}

func (f *Factory) ClearBaseProcedureMods() {
	f.baseProcedureMods = nil
}

func (f *Factory) AddBaseProcedureMod(mods ...ProcedureMod) {
	f.baseProcedureMods = append(f.baseProcedureMods, mods...)
}

func (f *Factory) ClearBaseSettingMods() {
	f.baseSettingMods = nil
}

func (f *Factory) AddBaseSettingMod(mods ...SettingMod) {
	f.baseSettingMods = append(f.baseSettingMods, mods...)
}
