// Code generated by BobGen sqlite v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"strings"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
)

var defaultFaker = faker.New()

func random_decimal_Decimal(f *faker.Faker) decimal.Decimal {
	if f == nil {
		f = &defaultFaker
	}

	return decimal.New(f.Int64Between(0, 1000), 0)
}

func random_float32(f *faker.Faker) float32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Float32(10, -1_000_000, 1_000_000)
}

func random_int32(f *faker.Faker) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_string(f *faker.Faker) string {
	if f == nil {
		f = &defaultFaker
	}

	return strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
}

func random_time_Time(f *faker.Faker) time.Time {
	if f == nil {
		f = &defaultFaker
	}

	year := time.Hour * 24 * 365
	min := time.Now().Add(-year)
	max := time.Now().Add(year)
	return f.Time().TimeBetween(min, max)
}
