// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListPatient = { id: string, type: string, name: string, chip_id: string, owner: string, phone: string, };
