// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { Procedure } from "./Procedure";

export type Patient = { id: string, type: string, name: string, gender: Gender, birth_date: string, chip_id: string, weight: number, castrated: boolean, last_modified: string, note: string, owner: string, owner_phone: string, procedures: Array<Procedure>, };
