// Code generated by tygo. DO NOT EDIT.

//////////
// source: view.go

export interface ViewProcedure {
  id: string;
  type: string;
  date: string;
  details: string;
  patientId: string;
}
export interface ViewListPatient {
  id: string;
  type: string;
  name: string;
  chipId: string;
  owner: string;
  phone: string;
}
export interface ViewPatient {
  id: string;
  type: string;
  name: string;
  gender: 'unknown' | 'male' | 'female';
  birthDate: string;
  chipId: string;
  weight: number /* float64 */;
  castrated: boolean;
  lastModified: string;
  note: string;
  owner: string;
  ownerPhone: string;
  procedures: ViewProcedure[];
}
export interface ViewError {
  error: string;
}
