// Code generated by tygo. DO NOT EDIT.

//////////
// source: view.go

export interface ViewProcedure {
  id?: number /* uint */;
  type?: string;
  date?: string;
  details?: string;
  patientId: number /* uint */;
}
export interface ViewListPatient {
  id: number /* uint */;
  type: string;
  name: string;
  chipId: string;
  owner: string;
  phone: string;
}
export interface ViewPatient {
  id?: number /* uint */;
  type?: string;
  name?: string;
  gender?: 'unknown' | 'male' | 'female';
  birthDate?: string;
  chipId?: string;
  weight?: number /* float64 */;
  castrated?: boolean;
  lastModified?: string;
  note?: string;
  owner?: string;
  ownerPhone?: string;
  procedures?: ViewProcedure[];
}
export interface ViewSetting {
  id?: number /* uint */;
  type: 'PatientType' | 'ProcedureType';
  value: string;
  index: number /* uint */;
}
export interface ViewError {
  error: string;
}
