// Code generated by tygo. DO NOT EDIT.

//////////
// source: module.go

export type SettingType = string;
export const PatientType: SettingType = "PatientType";
export const ProcedureType: SettingType = "ProcedureType";

//////////
// source: view.go

export interface ViewProcedure {
  id: any /* omit.Val */<number /* int32 */>;
  type: any /* omitnull.Val */<string>;
  date: any /* omitnull.Val */<string>;
  details: any /* omitnull.Val */<string>;
  patientId: any /* omitnull.Val */<number /* int32 */>;
}
export interface ViewPatient {
  id: any /* omit.Val */<number /* int32 */>;
  type: any /* omitnull.Val */<string>;
  name: any /* omitnull.Val */<string>;
  gender: 'unknown' | 'male' | 'female';
  age: any /* omitnull.Val */<any /* decimal.Decimal */>;
  chipId: any /* omitnull.Val */<string>;
  weight: any /* omitnull.Val */<number /* float32 */>;
  castrated: any /* omitnull.Val */<any /* decimal.Decimal */>;
  note: any /* omitnull.Val */<string>;
  owner: any /* omitnull.Val */<string>;
  ownerPhone: any /* omitnull.Val */<string>;
  procedures: ViewProcedure[];
}
export interface ViewSetting {
  id: any /* omit.Val */<number /* int32 */>;
  type: 'PatientType' | 'ProcedureType';
  value: any /* omitnull.Val */<string>;
  index: any /* omitnull.Val */<number /* int32 */>;
}
export interface ViewError {
  error: string;
}
